export const GTM_STRATEGY_PROMPT = `You are an expert GTM operator for early-stage startups.

Your job is to generate a complete Go-To-Market strategy that helps the founder get their FIRST paying user within 48 hours.

Product:
{PRODUCT_NAME}
{PRODUCT_DESCRIPTION}
{WEBSITE_URL}

ICP:
{ICP_JSON}

Return ONLY the JSON below:

{
  "gtm_summary": "",

  "top_channels_ranked": [
    {
      "channel": "",
      "why_it_matters": "",
      "expected_results": "",
      "difficulty": ""
    }
  ],

  "48_hour_plan": {
    "day_1": ["", "", ""],
    "day_2": ["", "", ""]
  },

  "messaging": {
    "primary_value_prop": "",
    "one_line_pitch": "",
    "email_subject_lines": ["", "", ""],
    "linkedin_openers": ["", "", ""],
    "reddit_post_hooks": ["", "", ""],
    "twitter_hooks": ["", "", ""]
  },

  "ideal_targets": {
    "titles": ["", ""],
    "industries": ["", ""],
    "communities": ["", ""],
    "search_queries": ["", ""]
  },

  "outreach_templates": {
    "cold_email": "",
    "linkedin_dm": "",
    "reddit_post": "",
    "twitter_pitch": ""
  },

  "launch_assets": {
    "landing_page_headline": "",
    "landing_page_subheadline": "",
    "product_hunt_tagline": "",
    "twitter_bio": ""
  },

  "risks_and_missteps": ["", ""],

  "success_metrics": {
    "first_48_hours": ["", ""],
    "first_7_days": ["", ""]
  }
}

Additional requirements:
- All messaging must be direct, pain-first
- All outreach templates must be short & founder-friendly
- Return ONLY valid JSON, no markdown, no code blocks, no explanations`;

export const ONE_LINE_MESSAGING_PROMPT = `You are a world-class positioning expert.

Using the ICP + GTM strategy below, generate three extremely short, high-conversion messaging lines founders can immediately use.

ICP:
{ICP_JSON}

GTM:
{GTM_JSON}

Return JSON only:

{
  "landing_page_headline": "",
  "value_prop_one_liner": "",
  "dm_opener": ""
}

Rules:
- 9–13 words
- Pain-first
- Outcome-driven
- No buzzwords
- Return ONLY valid JSON, no markdown, no code blocks`;

export const ACTION_CHECKLIST_PROMPT = `You will take a GTM Plan and turn it into a simple, actionable checklist founders can execute today.

Input:
{GTM_JSON}

Output JSON ONLY:

{
  "today": [
    "Specific action..."
  ],
  "tomorrow": [
    "Specific action..."
  ],
  "high_impact_actions": [
    "3 tasks with fastest path to customer"
  ],
  "nice_to_have": [
    "Optional tasks"
  ]
}

Rules:
- Every task ≤ 30 minutes
- Must be quantifiable (ex: "Send 15 DMs")
- Return ONLY valid JSON, no markdown, no code blocks`;

export const ICP_CARD_PROMPT = `You are designing a compact, visually appealing ICP summary card for founders to share on LinkedIn or Twitter.

Use the ICP JSON below:

{ICP_JSON}

Generate a summary card with:
- Product name
- ICP one-liner
- Top 3 pain points (short)
- Messaging hook (1 line)
- 3 places this ICP hangs out
- Footer: "Generated by LaunchKit 🚀"

Return ONLY this JSON:

{
  "card_title": "",
  "icp_line": "",
  "pain_points": ["", "", ""],
  "messaging_hook": "",
  "where_they_hangout": ["", "", ""],
  "footer": "Generated by LaunchKit 🚀"
}

Return ONLY valid JSON, no markdown, no code blocks`;
